### ISSUE TITLE
Add Alt+Tab

### ISSUE THREAD

**Issue by rux616** [rux616/karabiner-windows-mode#14]
~See title.~

This issue is to track adding "Alt+Tab" functionality.

**Comment by TheBugurtov** [comment]
> See title.

What a title? Alt+Tab not working for me

**Comment by rux616** [comment]
"See title" means "the title has the info" in this case.

**Comment by TheBugurtov** [comment]
Where is info? I didn't see it

**Comment by rux616** [comment]
> Where is info? I didn't see it

I've updated the text of the issue to better explain what its purpose is.

**Comment by nathang21** [comment]
Also one related shortcut that is different in windows:
Alt + Tab: Cycle open windows on OS
Ctrl + Tab: Cycle open tabs within App

Even if you swap the Control/Command(aka alt) on mac, getting both of these shortcuts to work the as expected is quite tricky.

**Comment by hansvb** [comment]
BUMP

**Comment by fab1o** [comment]
On Mac, go to your `user/.config/karabiner/karabiner.json`


Add this piece of json to your `"rules"` in `"complex_modifications"`

```json
{
    "description": "Option(Alt)+Tab as Switch Application (Command+Tab)",
    "manipulators": [
        {
            "from": {
                "key_code": "tab",
                "modifiers": {
                    "mandatory": [
                        "option"
                    ],
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "tab",
                    "modifiers": [
                        "left_command"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
},
```

**Comment by rux616** [comment]
@dangnhdev Because sometimes I am a bit of an idiot! 😅

I didn't even realise this code had been added and have been lax in keeping up with the issues. I'll carve out some time soon to do some upkeep and add new features/merge PRs.
