### ISSUE TITLE
Ctrl+F4

### ISSUE THREAD

**Issue by Will-W** [rux616/karabiner-windows-mode#24]
Ctrl+t works to open tabs in Chrome. From Windows I am used to closing them with Ctrl+F4. It would be great to add that.

**Comment by jacobisaliveandwell** [comment]
@Will-W You mean `Alt-F4`, right? `Ctrl-F4` usually closes the current window / tab.

**Comment by Will-W** [comment]
No - I want to close a tab (not the whole browser). Ctrl+t is implemented, I'm looking for the inverse - Ctrl+F4.

**Comment by rux616** [comment]
@Will-W I just pushed a change that _should_ address this, but I can't be 100% sure I got the right bundle ID for Chrome as I no longer have a Mac. Would you mind testing it for me?
