### ISSUE TITLE
Why are Terminals exempted?

### ISSUE THREAD

**Issue by samuelneff** [rux616/karabiner-windows-mode#26]
Would you mind explaining why Terminals are exempted from the shortcut remapping?

I saw the note in the readme, the original issue #15, as well as the addition for an alternate Ctrl+Shift+C/V for copy/paste issue #7. I don't understand why this is exempted though.

Thanks!

Sam

**Comment by rux616** [comment]
Sure! In a nutshell, applications inside the terminal (`bash`, `vim`, `nano`, `tmux`, etc.) are expected to handle their own inputs, which in many cases conflict with the karabiner bindings. For example, you type in ctrl+c and you expect that the shell handles it to send the proper interrupt, but if karabiner intercepts it, cmd+c is what would be sent instead which simply copies some text. This is unexpected behaviour, which is a Very Bad Thing(tm), hence terminal emulators are excepted (excluding the ctrl+shift+c/v commands and a few others of course) so they can have an interference-free experience.

**Comment by samuelneff** [comment]
Thanks for the explanation.
