### ISSUE TITLE
Language input change

### ISSUE THREAD

**Issue by GeorgeV220** [rux616/karabiner-windows-mode#50]
Add alt + shift to change input language

**Comment by bpeychev** [comment]
{
    "description": "Map Alt+Shift to Ctrl+Shift+Space to change input language.",
    "manipulators": [
        {
            "from": {
                "key_code": "left_shift",
                "modifiers": { "mandatory": ["left_alt"] }
            },
            "to": [
                {
                    "key_code": "spacebar",
                    "modifiers": ["left_control", "left_shift"]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "right_shift",
                "modifiers": { "mandatory": ["left_alt"] }
            },
            "to": [
                {
                    "key_code": "spacebar",
                    "modifiers": ["left_control", "left_shift"]
                }
            ],
            "type": "basic"
        }
    ]
}
