### ISSUE TITLE
"Win" rule might be broken

### ISSUE THREAD

**Issue by raxigan** [rux616/karabiner-windows-mode#68]
There is a [rule called "Win"](https://github.com/rux616/karabiner-windows-mode/blob/master/json/windows_shortcuts.json#L1002) (not mentioned in README), but it seems to be broken - it's not opening Launchpad for me. Based on karabiner [key codes list](https://github.com/pqrs-org/Karabiner-Elements/blob/main/src/apps/PreferencesWindow/Resources/simple_modifications.json) `command` cannot be used as `from.key_code`. The rule starts working after changing the key code to `left_command`.

@rux616 Could you please confirm my suspicions? I can open PR with a fix (and maybe some improvements) later on.

**Comment by rux616** [comment]
That bit was a relic from _way_ back when I first started this project (an attempt to address #13), and I had forgotten about cleaning it up. If you'd like to submit a PR to get it working, I'll be happy to review it.
