### ISSUE TITLE
iterm2 blocking cmd + number for opening app pinned to dock 

### ISSUE THREAD

**Issue by basanys** [rux616/karabiner-windows-mode#78]
Everything works as intended, until I enter iterm2 app. Once iterm is active cmd + number stops working until i click on some other app.
I am new to this, maybe someone can help me find solution for this. Thank you 

https://github.com/rux616/karabiner-windows-mode/assets/65812993/68676a2b-9d91-4027-8154-b1cd7c53ba39

**Comment by rux616** [comment]
Right now, this configuration is set so that Cmd+(Number) doesn't work in the Excepted Applications. I'll update it to allow Cmd+Number to work in IDEs and Terminal Emulators as well.
