### ISSUE TITLE
Deprecated: Please Use the New Fork for Latest Features

### ISSUE THREAD

**Issue by Strong-Foundation** [rux616/karabiner-windows-mode#93]
Hi everyone,

This repository has been deprecated, and it’s no longer actively maintained. The community, along with some of the original contributors, have moved to a new fork of this project with continued development and new features.

We highly recommend switching to the new repository for ongoing updates, bug fixes, and the latest enhancements:

**New Repository:** [Karabiner-Elements-Remapping](https://github.com/Strong-Foundation/Karabiner-Elements-Remapping)

The new repository includes many improvements, and we suggest migrating to it for a better experience with more features.

Thank you for your support, and we hope to see you on the new repo!

**Comment by rux616** [comment]
This repo isn't deprecated, I'm just slow at updating. If I deprecate it, there will be a note saying as such and the repo will be archived.

**Comment by Strong-Foundation** [comment]
Hi everyone,

I wanted to clarify that my intention with the new repository is to provide the community with an alternative option. While this repo is still active and I’m continuing to work on it, we understand that some users may prefer a project with faster updates, cleaner, and simpler code.

The new repository, **Karabiner-Elements-Remapping**, is designed with these goals in mind. It will be actively maintained with frequent updates and improvements, all while keeping things open source. We welcome anyone looking for a more streamlined experience, and we’re here to provide that choice.

Both repositories will remain open-source, and we want to ensure everyone has options that best suit their needs. Your feedback and contributions are always appreciated!

Best,  
@rux616

**Comment by rux616** [comment]
> Hi everyone,
> 
> I wanted to clarify that my intention with the new repository is to provide the community with an alternative option. While this repo is still active and I’m continuing to work on it, we understand that some users may prefer a project with faster updates, cleaner, and simpler code.
> 
> The new repository, **Karabiner-Elements-Remapping**, is designed with these goals in mind. It will be actively maintained with frequent updates and improvements, all while keeping things open source. We welcome anyone looking for a more streamlined experience, and we’re here to provide that choice.
> 
> Both repositories will remain open-source, and we want to ensure everyone has options that best suit their needs. Your feedback and contributions are always appreciated!
> 
> Best,
> @rux616

Just as an FYI to anyone that finds this in the future: This message might read like it's from me and I'd just like to be clear that it is not. (It's probably just an idiosyncrasy on Strong-Foundation's part, for which I bear no ill will whatsoever.)

**Comment by Strong-Foundation** [comment]
> > Hi everyone,
> > I wanted to clarify that my intention with the new repository is to provide the community with an alternative option. While this repo is still active and I’m continuing to work on it, we understand that some users may prefer a project with faster updates, cleaner, and simpler code.
> > The new repository, **Karabiner-Elements-Remapping**, is designed with these goals in mind. It will be actively maintained with frequent updates and improvements, all while keeping things open source. We welcome anyone looking for a more streamlined experience, and we’re here to provide that choice.
> > Both repositories will remain open-source, and we want to ensure everyone has options that best suit their needs. Your feedback and contributions are always appreciated!
> > Best,
> > @rux616
> 
> Just as an FYI to anyone that finds this in the future: This message might read like it's from me and I'd just like to be clear that it is not. (It's probably just an idiosyncrasy on Strong-Foundation's part, for which I bear no ill will whatsoever.)

In my experience, when the community finds a better version of the software that meets their needs more effectively, the focus tends to shift from the original author to the quality and usefulness of the new version. Users generally care less about who the original author was, and more about whether the software works well for them and provides the features they're looking for.

Once a project is open source, it's less about ownership and more about what benefits the community. If people are happy with the improvements, updates, or changes made to the software, they'll continue to use it regardless of the author’s identity. What matters is that the software meets their needs and remains actively maintained.

So, if your version of the software addresses user concerns, improves usability, or simply provides a better overall experience, that's what users will care about the most.
